# Generated by Django 4.0.3 on 2022-03-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todo'},
        ),
        migrations.AddField(
            model_name='todomodel',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is_done'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
